### PR TITLE
Adding license information

### PR DESCRIPTION
**Pull request by jnwng**
Precursor to addressing #2 - once the license information is added, I can go ahead and publish this on NPM.

PTAL @jpbetz @ankit

### CODE REVIEW

**Comment by ankit** [comment]
isn't a LICENSE file on the repo (https://github.com/coursera/scribe-plugin-placeholder/blob/master/LICENSE) sufficient or do we need the Copyright cruft as part of the header of each file?

**Comment by jnwng** [comment]
we need to add them to the top of every file, per the legal docs. see [coursera/courier](https://github.com/coursera/courier/blob/master/project/Build.scala#L1-L15)

**Comment by jnwng** [comment]
you'll see that on other libraries like [react](https://github.com/facebook/react/blob/master/src/React.js#L1-L10) too

**Comment by ankit** [comment]
ah ok :grimacing:

**Pull request merged**
